services:
  bot:
    build: ./bot
    container_name: rusdi-bot
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_PATH=/app/data
      - TZ=Asia/Jakarta
    depends_on:
      - edge-tts
    restart: unless-stopped

  web:
    build: ./web
    container_name: rusdi-web
    ports:
      - "80:3000"
    env_file:
      - .env
    environment:
      - DATABASE_PATH=/app/data
      - TZ=Asia/Jakarta
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  edge-tts:
    image: travisvn/openai-edge-tts:latest
    container_name: rusdi-edge-tts
    environment:
      - PORT=5050
      - DEFAULT_VOICE=id-ID-ArdiNeural
      - DEFAULT_LANGUAGE=id-ID
      - REQUIRE_API_KEY=False
      - DEFAULT_RESPONSE_FORMAT=mp3
      - DEFAULT_SPEED=1.0
    restart: unless-stopped
